### ISSUE TITLE
现在貌似不好使了

### ISSUE THREAD

**Issue by gaoguangbo** [96chh/Upgrade-ProcessOn#4]
现在貌似不好使了，出现邮箱后，一直卡着

**Comment by lniwn** [comment]
确实，出现邮箱后一直卡着

**Comment by chanwoood** [comment]
嗯，现在注册时，需要通过腾讯的滑动验证码。

**Comment by Donny2g** [comment]
现在更不好使了，加了20张后文件数量变成-8了

**Comment by zhuSilence** [comment]
有 mac 版么

**Comment by stevenlii** [comment]
不好使啊，
` C:\Users\MC>python processon.py
Traceback (most recent call last):
  File "processon.py", line 81, in <module>
    make(getuser())
  File "processon.py", line 73, in make
    domain = getdomain()
  File "processon.py", line 29, in getdomain
    return random.choice(domains)
  File "D:\Users\MC\Anaconda3\lib\random.py", line 261, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence`
