### ISSUE TITLE
不知道是不是引起官方注意了

### ISSUE THREAD

**Issue by the-third-brother** [96chh/Upgrade-ProcessOn#5]
Traceback (most recent call last):
  File "processon.py", line 82, in <module>
    make(getuser())
  File "processon.py", line 73, in make
    domain = getdomain()
  File "processon.py", line 28, in getdomain
    domains = [tag.text for tag in soup.find(id="domain").find_all("option")]
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by Vancause** [comment]
I have got the same error!
How can I solve it..?

**Comment by the-third-brother** [comment]
> I have got the same error!
> How can I solve it..?

The reason you got it is just because you excute the program file frequently in a short time. Do it again after a few days. It really works for me.
